### ISSUE TITLE
Nas listas, markdown é truncado antes de renderizar

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#1]
O filtro "description_markdown_preview" trunca o texto antes de renderizar, o que provoca em alguns casos uma exibição  incompleta e com partes da marcação original visíveis. Exemplo no relato original abaixo.

---

Relato original:

> _Bug - texto de visualização dos projetos_
> 
> Na segunda página da aba de Projetos (http://maps.mootiro.org/project?page=2), o texto do projeto Redes de Promoção dos Direitos da Criança e do Adolescente está com bug. 
> Na página do próprio projeto um trecho do texto ("campo da promoção, garantia e defesa dos direitos de crianças e adolescentes..."), no primeiro parágrafo, possui link. Na página em que os projetos estão listados, na aba de projeto, esse mesmo texto apresenta um colchete onde iniciaria o texto linkado.
>  
> Estou usando o Chrome.

**Comment by LuizArmesto** [comment]
Só comentando que eu editei o título e o conteúdo da issue para ficar mais claro para nós desenvolvedores qual é e onde está o problema.

**Comment by ghost** [comment]
Acho que a solução disso deveria ser melhorar o layout da página de listagem, onde não teria o campo description.
Isso, ao meu ver, é melhor do que tentar quebrar o markdown em um ponto "seguro"...

**Comment by andersoncardoso** [comment]
vou marcar como wontfix pois isso será resolvido com a mudança de interface das listagens.
