### ISSUE TITLE
Página inicial - erro em "Para que usar?"

### ISSUE THREAD

**Issue by aimeesf** [it3s/mootiro-maps#100]
O 5º div (de Guia do Bairro) está abaixo dos outros (deveria estar ao lado)

Windows
IE 8.0.7601.17514
Firefox 18.0.2
Chrome 25.0.1364.152 m

![para-que-bugar](https://f.cloud.github.com/assets/301256/250489/a9e37376-8b4b-11e2-9b96-1c8e7cbde938.png)

**Comment by ghost** [comment]
@aimeesf eu fiz deploy agora. Confirma que está consertado?

**Comment by aimeesf** [comment]
@acasimiro tudo certo
