### ISSUE TITLE
Erros em "ver no mapa" - Recurso

### ISSUE THREAD

**Issue by aimeesf** [it3s/mootiro-maps#101]
Na página de um recurso, ao clicar em ver no mapa, encontro os seguintes problemas:

Chrome Versão 25.0.1364.152 m - Mapa abre só em metade da página

![rec-mapa-chrome](https://f.cloud.github.com/assets/301256/250744/52a75b6a-8b53-11e2-8048-584931f4b161.png)

IE 8.0.7601.17514 - não aparece o mapa. abrem os campos de login (cliquei no ícone de "Erro na página" pra mostrar o que a janela dizia)

![rec-mapa-ie](https://f.cloud.github.com/assets/301256/250755/ccc51c98-8b53-11e2-9972-8c645c38779c.png)

Firefox 18.0.2 - não aparece o mapa

![rec-mapa-firefox](https://f.cloud.github.com/assets/301256/250757/d4a2ec60-8b53-11e2-9f32-ac3c24dec8d8.png)

**Comment by LuizArmesto** [comment]
Ainda apresenta erro no ie 8. No chrome, firefox e ie 9+ eu testei aqui e está funcionando a versão de desenvolvimento.

Precisamos avaliar quais versões do ie daremos suporte. Fechando o issue...
