### ISSUE TITLE
Botão para pessoas adicionar-se como colaborador de um projeto

### ISSUE THREAD

**Issue by everton137** [it3s/mootiro-maps#102]
Para participar de um projeto, notei que tem que pedir para o administrador do projeto ou ele mesmo colocar.

Sugiro um botãozinho num projeto do tipo "Torne-se um colaborador".

**Comment by LuizArmesto** [comment]
A ideia é que um usuário seja automaticamente adicionado como colaborador quando ele adicionar algum objeto ao projeto.

**Comment by pauloandreferreirasouza** [comment]
projet
