### ISSUE TITLE
No mapa do projeto o usuário que adicionou mais de um objeto aparece várias vezes como colaborador

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#103]
http://maps.mootiro.org/project/83/map
- Aparece duas vezes Daniela - somente deve aparecer uma vez
- aparecem 243 organizações no balão da Daniela - somente deve aparecer um

**Comment by LuizArmesto** [comment]
Fica mais fácil de organizar as tarefas abrindo uma issue diferente para cada problema e não usando a mesma para relatar vários bugs. Nessa, por exemplo, o fato de aparecer usuário duplicado na listagem não tem relação com o conteúdo do balão do usuário.

**Comment by elaste** [comment]
ok, Luiz.

vc já abriu outro ticket ou quer que eu faça?

2013/3/18 Luiz Armesto notifications@github.com

> Fica mais fácil de organizar as tarefas abrindo uma issue diferente para
> cada problema e não usando a mesma para relatar vários bugs. Nessa, por
> exemplo, o fato de aparecer usuário duplicado na listagem não tem relação
> com o conteúdo do balão do usuário.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/103#issuecomment-15083790
> .

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org

**Comment by LuizArmesto** [comment]
Já abri (#109). No github ele aparece relacionado com um link para ele.
