### ISSUE TITLE
Problema de importação de KML com múltiplas LineString

### ISSUE THREAD

**Issue by ghost** [it3s/mootiro-maps#105]
**Eu vejo:** "Informação geométrica não disponível"
**Eu deveria ver:** um mapa com pelo menos 2 linhas

**Como reproduzir o erro:**

```
fab production get_a_db_copy
fab recreate_db
psql mootiro_komoo < ./backupdb_production_<date>.sql
git pull origin stable
fab run
```
- Acessar a página http://localhost:8001/importsheet/45/insert (vai demorar um pouco)
- A página dos seguintes recursos estará com o mapa quebrado:
  - Ciclofaixa Parque do Povo - Praça Durval Pereira
  - Ciclofaixa de Lazer - Centro
  - Ciclofaixa de Lazer Paulista - Vergueiro - Liberdade
  - Ciclofaixa entre Parques
  - Ciclofaixa de Lazer - Trecho Guarapiranga
  - Ciclofaixa de Lazer Zona Leste
  - Ciclofaixa de Lazer Butantã

**Comentários:**
- A importação contém 33 recursos (todos com geometria) mas no mapa do projeto só aparecem 26 objetos. 33 - 26 = 7 recursos com problema acima.
- Todos os outros objetos tem sua visualização correta (eu chequei)
- Os recursos com problema tem em comum o fato de que na importação contém mais de uma linha em sua geometria.
- Se quiser dar uma olhada no kml que gerou isso entre [aqui](https://www.google.com/fusiontables/data?docid=1wfWq-sV7nyChJl0cFZqQST0_OITHdPqsHztsDkA#rows:id=1) e procure por algum dos identificadores acima.

**Comment by ghost** [comment]
@LuizArmesto há uma certa urgência nesse ticket para a Dani conseguir importar uns conteúdos. Consegue dar uma olhadinha rápida?

**Comment by LuizArmesto** [comment]
Feito, porém não atualizei o servidor.

**Comment by ghost** [comment]
Ae! Não precisa atualizar não. Eu faço isso amanhã.
Valeu! ;)

Não deveria fechar o issue?
