### ISSUE TITLE
Busca por raio: distancia desconfigurada ao abrir lista de needs

### ISSUE THREAD

**Issue by leaa** [it3s/mootiro-maps#113]
Na busca po raio, ao abrir a lista das necessidades, desconfigura a caixinha com o raio escolhido: uma parte da caixinha com o m (metros) fica uma linha abaixo.

**Comment by LuizArmesto** [comment]
Qual o sistema operacional e o navegador usados?

**Comment by leaa** [comment]
Usei o Firefox e o tem o Xubuntu rodando no meu notebook. Nao testei em outros computadores ainda.

**Comment by LuizArmesto** [comment]
Não consegui reproduzir o problema, mas fiz uma alteração no css que acho que previne que algo do tipo ocorra.

Ainda não está em produção mas já vou fechar o issue. Se depois de atualizar o servidor continuar a gente reabre.
