### ISSUE TITLE
Colaborador do projeto - eventos que fazem com que uma pessoa se torne colaboradora

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#115]
A pessoa que edita o texto do projeto também deve se tornar colaborador. Quem importa objetos para o projeto, também deve ser um colaborador.

**Comment by LuizArmesto** [comment]
Se tornar colaborador importando um objeto está funcionando, certo? Ou está com bug nisso?

**Comment by elaste** [comment]
Não, não está funcionando.
O evento aparece na thread de últimas ações do usuário, mas ele não se
torna colaborador.

On Mon, Mar 25, 2013 at 1:27 PM, Luiz Armesto notifications@github.comwrote:

> Se tornar colaborador importando um objeto está funcionando, certo? Ou
> está com bug nisso?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/115#issuecomment-15403849
> .

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org

**Comment by LuizArmesto** [comment]
Acabei de testar em staging incluindo o objeto http://staging.maps.mootiro.org/need/82 no projeto http://staging.maps.mootiro.org/project/24 e fui incluído no projeto como colaborador.

Teria um exemplo de projeto/usuário/objeto no qual isso não está funcionando?

**Comment by LuizArmesto** [comment]
Acho que entendi, o importar não é indo pela interface e incluindo um objeto no projeto, é pela funcionalidade do @acasimiro de importar do google docs? É isso?

**Comment by elaste** [comment]
sim! estava me referindo a isso.

2013/3/25 Luiz Armesto notifications@github.com

> Acho que entendi, o importar não é indo pela interface e incluindo um
> objeto no projeto, é pela funcionalidade do @acasimirohttps://github.com/acasimirode importar do google docs? É isso?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/115#issuecomment-15404843
> .

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org
