### ISSUE TITLE
Bug no "ver no mapa" do objeto

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#123]
Ao clicar no "ver no mapa" nao aparece o ponto do objeto no mapa, somente os objetos relacionados.

**Comment by ghost** [comment]
Qual o link?

**Comment by elaste** [comment]
Estou em qualquer página de conteudo, por exemplo: http://maps.mootiro.org/organization/1506 e clico em "ver no mapa" - aí aparece a página dos objetos relacionados mas sem o próprio objeto.
