### ISSUE TITLE
Sistema para recuperação de senha

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#126]
É preciso haver um processo para recuperação de senha para os usuário que optarem por cadastrar uma conta no MootiroMaps. (digo isso porque quem loga com o Facebook ou Google não possuem senha)

O processo deve ser da seguinte forma:
- Na tela de login deve haver um link "Esqueci a senha" abaixo de "Não possui uma conta? Registre-se!"
- Vai para uma tela em que o usuário deve digitar o e-mail que foi cadastrado
- O sistema gera um link aleatório (algo como /user/recover/515c7a718bb633a22600064e) e enviá-lo para o usuário por e-mail
- O link aleatório levará a uma tela em que o usuário pode definir uma nova senha sem precisar digitar a atual, claro. (talvez seja possível reaproveitar algo da tela de definição de nova senha na edição do perfil do usuário)

**Comment by ghost** [comment]
Não falta só o link, falta todo o processo de recuperação de senha. Editando.

**Comment by andersoncardoso** [comment]
isso é algo q talvez o pessoal da UnB possa trabalhar em cima.

**Comment by ghost** [comment]
Concordo.

**Comment by LuizArmesto** [comment]
+1

**Comment by LuizArmesto** [comment]
Parece estar feito
