### ISSUE TITLE
Bug no carregamento da página de um projeto

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#127]
Ao carregar um projeto, o sistema mostra no lugar do mapa, a palavra "Campanha". Depois aparece o mapa, com foco em SP.

Além disso, as abas - dados e colaboradores ficam desagregados.

O comportamento desejado é:

Quando não tiver carregado parece uma mensagem "carregando". Quando tiver tudo carregado o sistema mostra a visualização correta - as abas sem serem desagregadas e o mapa com foco no local certo.

**Comment by LuizArmesto** [comment]
Remover a palavra campanha, que pisca no inicio, é trivial.

Exibir uma mensagem de carregando e só depois mostrar tudo pronto não é tão trivial.

Esse problema ocorre mais visivelmente em conexões mais lentas ou páginas de projetos com muitos objetos associados (pois são páginas mais pesadas), quando parte do html da página já foi carregado e renderizado pelo navegador mas os arquivos de javascript, imagens, informações geométricas, etc, ainda estão sendo carregados. Há uma demora para que o javascript que inicializa o mapa, exibe os pontos no mapa centralizando-o e inicializa as abas seja executado.

Uma implementação possível dessa sugestão, que me veio rapidamente e não avaliei muito os prós e contras, seria forçar um "display:none" no conteúdo, deixando apenas uma div com o texto "carregando" e o cabeçalho visíveis, logo que a página começa a ser carregada, daí assim que a página terminar de ser carregada e o javascript que inicializa as abas e o mapa terminar de ser executado muda-se a regra "display" para tornar o conteúdo visível e removemos a div "carregando". Não sei se essa é uma boa solução, além disso tem o problema que o mapa não funciona direito quando inicializado escondido, tendo que atualizá-lo depois de torná-lo visível.
