### ISSUE TITLE
Recuperação de senha

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#128]
O Maps ainda não oferece funcionalidade para recuperação de senha.
junto a caixa do login deve ter um link para recuperação da senha.
O usuário será redirecionado para uma página onde pode inserir seu e-mail.
Há um botão para enviar.

O sistema envia um link para o e-mail da pessoa.
Clicando no link a pessoa chega em um lugar onde pode recuperar a senha: definir a nova senha e repetir. O sistema valida se as duas senhas inseridas são iguais.
Há ainda um aviso que a senha foi alterada.

**Comment by ghost** [comment]
Duplicado de #126
