### ISSUE TITLE
Problema referente à representação das linhas no mapa

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#129]
Quando se mapeia uma linha que não esteja reta, o ponto pertencente à linha não fica em cima do objeto, e sim do lado dele.

Isso complica que o usuário possa associar o ponto com o objeto correspondente. o comportamento desejado é que o ponto fique em cima do objeto ao qual pertence.

Exemplo: http://maps.mootiro.org/project/85/map

**Comment by LuizArmesto** [comment]
Confirmado, pois o posicionamento do ponto não distingue o tipo de geometria, é criado um retângulo imaginário ao redor da geometria e o ponto é colocado no centro desse retângulo. Esse caso de não ficar em cima da geometria pode acontecer também com polígonos côncavos, mas é menos provável.

Ter que calcular um local que garanta que o ponto fique sobre a geometria pode tornar o mapa um pouco mais lento no carregamento, no caso de mutas geometrias sendo exibidas, pois serão cálculos a mais a serem feitos para cada objeto.

Esses pontos associados a outras geometrias são realmente importantes? Pergunto isso pois me parece que a simples existência deles já pode causar confusão, batendo o olho eu não saberia dizer qual pondo é uma representação do próprio polígono e qual ponto é um objeto separado, de mesmo tipo, sobreposto ao polígono.

**Comment by LuizArmesto** [comment]
Fechando por falta de feedback e por possíveis implicações de performance.
