### ISSUE TITLE
Palavras-chave dos projetos não funcionam

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#13]
No projeto http://beta.maps.mootiro.org:5000/project/24 cliquei nas palavras-chave, mas não acontece nada.

http://beta.maps.mootiro.org:5000/project/24#?sorters=name&filters=tags&tags=Fam%EDlia

O sistema deve mudar para a listagens dos projetos com essa palavra-chave selecionada.

**Comment by ghost** [comment]
Already closed.
