### ISSUE TITLE
Edição do mapa, falta de atualização do pequeno mapa

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#130]
Quando os usuários editam a geometria de um ponto e clicam em avançar o pequeno mapa não atualiza. O ponto somente atualiza quando o usuário clicar em enviar. Isso é confuso. Deveria ter algum feedback visual que a edição foi sucedida.

**Comment by LuizArmesto** [comment]
Poderia dar um passo a passo de como reproduzir esse comportamento e qual sistema operacional e navegador foram usados? Eu testei no maps em produção e sempre que modifiquei a geometria e cliquei em avançar o mapa de preview foi atualizado. Não cliquei em salvar nenhuma vez.

**Comment by LuizArmesto** [comment]
Fechando por falta de feedback

**Comment by elaste** [comment]
haha - vou reabrir, Luiz

não tinha visto seu comentário.

On Mon, Jul 22, 2013 at 5:01 PM, Luiz Armesto notifications@github.comwrote:

> Fechando por falta de feedback
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/130#issuecomment-21371360
> .

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Fone: 0055-11-36285787
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
prestandocontas.org
maps.mootiro.org http://mootiro.org
it3s.org
