### ISSUE TITLE
Problema no mapa - Filtrar por tipo

### ISSUE THREAD

**Issue by aimeesf** [it3s/mootiro-maps#132]
O mapa começa carregando os poligonos de comunidades. Como demora um pouco e as comunidades não me interessavam, desmarquei o filtro e esperei carregar os demais objetos (necesidades, recursos e organizações), mas nada mais carregou: 

![003](https://f.cloud.github.com/assets/301256/586793/09d8f53c-c957-11e2-9fe8-dc08dd0089be.png)

Para faze-los aparecer, tive que desmarcar um filtro...

![004](https://f.cloud.github.com/assets/301256/586794/09fb0212-c957-11e2-9ce4-0422bf65e542.png)

... e depois marca-lo de novo.

![005](https://f.cloud.github.com/assets/301256/586795/0a17efbc-c957-11e2-88eb-e514578107fa.png)

Além disso, quando dou zoom poligonos somem novamente. (001.png)

![001](https://f.cloud.github.com/assets/301256/586792/09d9d5a6-c957-11e2-8473-b106b82f694a.png)

**Comment by aimeesf** [comment]
Chrome Version 27.0.1453.93

Mac OS 10.6.8

**Comment by LuizArmesto** [comment]
Fechando pois reescrevi boa parte do código dos filtros (ainda não em produção)
