### ISSUE TITLE
Visualização no mapa de um recurso

### ISSUE THREAD

**Issue by aimeesf** [it3s/mootiro-maps#133]
Ao tentar visualizar um recurso (nesse exemplo, http://maps.mootiro.org/resource/2055), o mapa começa carregando o poligono certo, mas depois é tomado por poligonos de comunidades e o recurso desaparece (tirei o primeiro screenshot enquanto ainda carregava, o segundo quando terminou)

![cicl-1](https://f.cloud.github.com/assets/301256/586852/5e024784-c958-11e2-9820-07a5b6032d06.png)
![cicl-2](https://f.cloud.github.com/assets/301256/586853/5e21b3bc-c958-11e2-9e77-ba168c23f147.png)

**Comment by LuizArmesto** [comment]
duplicado de #123
