### ISSUE TITLE
Erro na criação de conta

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#135]
O Email de verificação da conta de e-mail do usuário vai para a caixa de spam e aparentemente está sendo enviado direto do servidor ao invés de usar o mailgun.

Ele está sendo enviado ao mesmo tempo que o e-mail de boas-vindas. O sistema deve primeiro enviar a verificação da senha e ao concluir isso, deve enviar o email de boas-vindas.

**Comment by LuizArmesto** [comment]
O servidor já está enviando o email de validação pelo mailgun.
