### ISSUE TITLE
vídeo do youtube/vimeo embed

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#136]
Deve ser possível fazer o embed de vídeos do Youtube ou Vímeo para dentro de um objeto ou projeto do maps.

Para isso, na tela de edição deve existir um campo, onde o usuário pode definir um ou mais de um links do embed.
- Precisamos fazer a tela da edição e a tela de visualização dos vídeos que foram adicionados.

**Comment by LuizArmesto** [comment]
Feito em staging, entrará em produção na próxima atualização após os testes.
