### ISSUE TITLE
Possibilidade de "merge" entre objetos

### ISSUE THREAD

**Issue by LuizArmesto** [it3s/mootiro-maps#139]
Atualmente temos vários casos de objetos duplicados, como por exemplo alguns distritos da cidade de São Paulo. Seria bom ter um mode de unir as várias cópias em um único objeto e atualizar as referências.

**Comment by elaste** [comment]
como poderá funcionar isso? - é possível mostrar uma lista com objetos potencialmente identicos para facilitar a curadoria dos conteúdos?
