### ISSUE TITLE
No projeto link do mapa está quebrado

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#14]
Na página do projeto, o link "ver no mapa" leva até o Spock.

http://beta.maps.mootiro.org:5000/project/9

**Comment by elaste** [comment]
esse erro não acontece em outros projetos, testei com Aids e Comunidades (http://beta.maps.mootiro.org:5000/project/6)  e Ação Família (http://beta.maps.mootiro.org:5000/project/24), e o erro não acontece.
