### ISSUE TITLE
Normalização de palavras-chave

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#146]
Precisamos
- converter as palavras-chave para minúsculo
- tirar os espaços em branco em excesso na frente e no final da palavra-chave
- tirar espaços em branco em excesso no meio das palavras-chave
- fazer o merge entre as mesmas palavras-chave
- converter os links no sistema que apontam para páginas de busca para minúsculo para não serem quebrados

**Comment by andersoncardoso** [comment]
Feito, esta em staging então vou fechar
