### ISSUE TITLE
Botão de adicionar a um projeto deve estar no campo de configuração da busca

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#149]
O botão de adicionar a um projeto deve estar no local onde se configura a busca. Ele deve estar cinzento/inativo quando nada for configurado ou quando a busca retorna uma lista vazia e ativo/verde quando há resultados.

**Comment by LuizArmesto** [comment]
Já está feito. certo? Fechando pois testei no staging e me pareceu ok. :)

**Comment by andersoncardoso** [comment]
:+1:
