### ISSUE TITLE
Mudança do idioma de interface

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#151]
Vi que às vezes o idioma muda na hora de logar/deslogar.
Eu configurei como idioma de interface "Português" no meu usuário (user/2)
Acessei o sistema e ele estava em Português. Quando me loguei pela primeira vez ele mudou o idioma para Inglês (usando o Gmail para login) - isso não faz sentido porque meu idioma é português.
Depois o sistema demonstrou um comportamento aleatório - ele às vezes mudava o idioma durante o login e às vezes durante o logout. 

Ao meu ver, o funcionamento deve ser assim:

Se o sistema tiver em inglês, ele deve mudar para o idioma do usuário assim que ele se logar. Por exemplo, se o sistema tiver em inglês ao acessar, deve mudar para português quando eu me logar, já que meu idioma configurado é português.
No entanto, quando eu me deslogar ele não deve mudar o idioma, mas deve utilizar a última configuração que eu usei e manter.

**Comment by LuizArmesto** [comment]
O problema de aleatoriedade acho que resolvi (era um middleware que acho acabou deixando de ser carregado em algum merge, coloquei de volta).

Sobre o logout, não mudar o idioma significa continuar com o do último usuário que havia se logado ou continuar com o que estava antes do último usuário se logar? Atualmente está do segundo modo.
