### ISSUE TITLE
Adicionar a um projeto botão na aba de projetos

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#163]
http://maps.mootiro.org/project/list/?sorters=name&filters=tags&tags=educa%E7%E3o

Esse botão não deve existir na página de projetos.
Somente confunde o usuário.

**Comment by andersoncardoso** [comment]
Isso cabou indo "de graça" junto com a seção de filter.. mas realmente não
faz sentido.

2014-03-06 10:34 GMT-03:00 elaste notifications@github.com:

> http://maps.mootiro.org/project/list/?sorters=name&filters=tags&tags=educa%E7%E3o
> 
> Esse botão não deve existir na página de projetos.
> Somente confunde o usuário.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/163
> .

## 

Anderson Pierre Cardoso
Software Engineer - IT3S / University of Sao Paulo

_http://www.apierrecardoso.com http://www.apierrecardoso.com_
twitter: _@apierre_cardoso_ https://twitter.com/#%21/apierre_cardoso
