### ISSUE TITLE
Minimapa não funciona em alguns projetos

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#17]
http://beta.maps.mootiro.org:5000/project/6 - não mostra todos os objetos vinculados
http://beta.maps.mootiro.org:5000/project/11 - não aparece nenhum ponto no minimapa
http://beta.maps.mootiro.org:5000/project/15 - não aparece nenhum ponto no minimapa
http://beta.maps.mootiro.org:5000/project/12 - no minimapa não aparece nada
http://beta.maps.mootiro.org:5000/project/2 - somente aparecem as comunidades, mas as organizações e necessidades não ...

**Comment by LuizArmesto** [comment]
Os projetos que apresentam este problema também apresentam problema na visualização no mapa grande, centralizando-o no local errado.
