### ISSUE TITLE
Não é possível editar o nome da camada depois

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#175]
Uma vez definido o nome da camada, o campo não é mais editável.
Também, se o usuário começa definindo uma palavra-chave, ele depois não pode mais definir um nome para a palavra-chave.

**Comment by LuizArmesto** [comment]
Qual navegador, versão e sistema operacional ocorre isso?

**Comment by LuizArmesto** [comment]
Provavelmente é problema entre o Firefox e o jQuery UI Sortable. Vou verificar.

**Comment by elaste** [comment]
Firefox 28.0, Firefox for Ubuntu canonical 1.0, no Ubuntu, versão 64
