### ISSUE TITLE
Erro com relações duplas

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#177]
Alguns objetos têm múltiplas relações entre elas, por exemplo uma ONG pode ser membro de uma rede é também receber financiamento da mesma. Atualmente, o sistema somente permite uma relação. Quando é configurado uma segunda relação, a primeira é sobrescrita.

**Comment by elaste** [comment]
Esse problema é especialmente grave com os investimentos: uma organização pode receber mais de um investimento de um financiador.

**Comment by andersoncardoso** [comment]
solved => https://github.com/it3s/mootiro-maps/commit/a0b6e1712aaee87c158a291bb52d7ce762e1125f
