### ISSUE TITLE
Campo mark-down nos metadados dos investimentos

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#179]
Seria interessante ter um campo mark-down para os metadados dos investimentos. Assim podemos também inserir os links para as fontes e descrever o investimento. Esses dados (texto mark-down) existiam também no maps referente ao investimento - ao remover o investimento, essas informações foram perdidas e somente foi mantido o título do investimento.

**Comment by andersoncardoso** [comment]
salvo os dados de description na migração, mas como discutido para adicionar muitas instancias do markdown editor na mesma página, vai fica como campo simples por enqto.
