### ISSUE TITLE
Organização duplicada na listagem do mapa

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#18]
Na listagem que aparece do lado esquerdo do mapa, a organização está duplicada.

http://beta.maps.mootiro.org:5000/organization/2232/related

**Comment by andersoncardoso** [comment]
aconteceu algo bem peculiar aqui, A organização entrou com um investimento nela mesma, por isso apareceu duas vezes. Uma vez é referente ao ponto no mapa, a outra referente ao 'investimento'.

**Comment by andersoncardoso** [comment]
vou marcar como wont fix pois é uma situação muito única que provavelmente não vai ocorrer com dados reais (uma organizacao não tem pq cadastrar um investimento dela nela mesma). E essa visualização irá mudar em breve com a interface.
