### ISSUE TITLE
Erro ao adicionar organização.

### ISSUE THREAD

**Issue by ivesrocha** [it3s/mootiro-maps#190]
Ao mapear a organização Centro Cultural Batan Efrata (http://maps.mootiro.org/organization/17311), após preencher todo o formulário e clicar para enviar o ponto não é criado.  No topo da página aparece "Erro:O sistema já possui uma organização com este nome". 

Diante disto usei a barra de procura (novamente, pois já tinha pesquisado antes de criar o ponto) e não obtive resultado. Tentei alterar o nome da organização e sempre aparecia a msm mensagem de erro. Depois de alguns minutos, todas as tentativas apareceram no mapa (ex: http://maps.mootiro.org/organization/17313 e http://maps.mootiro.org/organization/17314) 

Aconteceu mais de uma vez e com mais de um usuário. (como este ponto: http://maps.mootiro.org/organization/17293 - mas apagamos os replicados) Tem acontecido algo parecido também quando tento adicionar um ponto a um Mapa de Projeto: clico em adicionar a um projeto, seleciono o projeto, salvo a mudança mas o projeto só aparece no perfil do ponto depois de um tempo de adicionado.

**Comment by andersoncardoso** [comment]
Oi Ives, nós estamos com algum problema na infraestrutura do Maps q ainda
não encontramos. Por isso estão ocorrendo tantos problemas o Luiz está
verificando nesse momento

Em 6 de agosto de 2014 15:23, Ives Rocha notifications@github.com
escreveu:

> Ao mapear a organização Centro Cultural Batan Efrata (
> http://maps.mootiro.org/organization/17311), após preencher todo o
> formulário e clicar para enviar o ponto não é criado. No topo da página
> aparece "Erro:O sistema já possui uma organização com este nome".
> 
> Diante disto usei a barra de procura (novamente, pois já tinha pesquisado
> antes de criar o ponto) e não obtive resultado. Tentei alterar o nome da
> organização e sempre aparecia a msm mensagem de erro. Depois de alguns
> minutos, todas as tentativas apareceram no mapa (ex:
> http://maps.mootiro.org/organization/17313 e
> http://maps.mootiro.org/organization/17314)
> 
> Aconteceu mais de uma vez e com mais de um usuário. (como este ponto:
> http://maps.mootiro.org/organization/17293 - mas apagamos os replicados)
> Tem acontecido algo parecido também quando tento adicionar um ponto a um
> Mapa de Projeto: clico em adicionar a um projeto, seleciono o projeto,
> salvo a mudança mas o projeto só aparece no perfil do ponto depois de um
> tempo de adicionado.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/it3s/mootiro-maps/issues/190.

## 

Anderson Pierre Cardoso

http://goog_730476546
http://andersoncardoso.github.io  |  @apierre_cardoso
http://twitter.com/apierre_cardoso

**Comment by ivesrocha** [comment]
Ok! Por favor avise quando encontrarem, para que eu possa dar uma resposta
aos usuários que estão com dificuldades (e também para continuar usando a
plataforma).

Em 6 de agosto de 2014 15:44, Anderson Pierre Cardoso <
notifications@github.com> escreveu:

**Comment by andersoncardoso** [comment]
@ivesrocha acho q agora deve estar normal novamente. O @LuizArmesto encontrou um problema no nosso message queue q fazia as requisições ficarem "empacadas" em qquer ação de save.
testa ai e me diz se agora ta tdo bem

**Comment by ivesrocha** [comment]
Funcionou. Mto obrigado.
