### ISSUE TITLE
Adicionando itens ao mapa de projeto

### ISSUE THREAD

**Issue by ivesrocha** [it3s/mootiro-maps#194]
Pessoal, tentei adicionar este item http://maps.mootiro.org/organization/17441# a este projeto http://maps.mootiro.org/project/417 através do botão da página de descrição da organização e não consegui. Cliquei no botão, escrevi o nome do projeto, selecionei e salvei, mas ainda assim não apareceu na lista de Mapas de Projeto (organização), nem na lista de conteúdo do projeto.

Tentei em outro projeto e consegui.

A diferença entre os dois projetos, pelo que pude perceber, é que um deles é anterior à personalização e o outro (o q está dando problema) é posterior. Diante isso, tentei criar camadas personalizadas, e mesmo assim não deu certo.

Como faço então, para adicionar itens aos novos mapas de projeto?

**Comment by ivesrocha** [comment]
obs: tentei adicionar diversos outros pontos ao mapa novo, tendo o mesmo resultado.

**Comment by andersoncardoso** [comment]
@LuizArmesto isso consertar o problema de adição da Analice?
vc deployou esse fix?
se sim.. eu mesmo adiciono os dados no mapa dela para a apresentação q ela tem amanhã.

**Comment by LuizArmesto** [comment]
@andersoncardoso  Sim. Acabei de fazer o depoy e adicionei o objeto de santos no mapa e foi ok.

**Comment by ivesrocha** [comment]
Como faço para adicionar? Estou tentando adicionar a unidade de Assis via
botão "mapas de projeto", sem sucesso.
Em 02/09/2014 00:22, "Luiz Armesto" notifications@github.com escreveu:

**Comment by andersoncardoso** [comment]
@LuizArmesto :+1:  x 1000 =D

**Comment by LuizArmesto** [comment]
Tinha faltado uma outra correção relacionada ao mesmo problema (uma que corrigia para projetos vazios e outra para  projetos já com algum conteúdo). Agora o servidor já está atualizado com ambas e não deve apresentar mais problemas para adicionar conteúdos nos projetos.
