### ISSUE TITLE
Problema com links do Google Docs no Markdown

### ISSUE THREAD

**Issue by Clari-zz** [it3s/mootiro-maps#2]
O link deveria abrir para um documento de visualização pública porém quando se clica não funciona e quando tenta abrir em uma nova aba (botão direito) ou abre uma página de documento em branco ou mostra que o documento não existe.

O que está acontecendo é que o link... (https://docs.google.com/document/d/1jIjeBNkNl27YH4zHENp5VEozY_cJUlMTDcduU9vrb_g/edit%20&quot;Entrevista%20realizada%20com%20Francisco%20Carlos%20no%20dia%2006_09_2012&quot;), 
após edit, cria um novo código, isso em todos eles que são anexados nas unidades das organizações abaixo:
- CCA 120 (Cardápio do CCAs, Entrevista realizada com Francisco Carlos no dia 06_09_2012 - links)
- CCA Pam (Entrevista realizada com Fábio Rodrigues no dia 21/08/2012, Cardápio dos CCAs - link)

OBS.: CCA Parceiros, só abre quando se clica com botão direito, é necessário que funcione assim que o usuário clicar com o botão esquerdo normalmente.

Obrigada.
## 

Titulo original: Link não funciona no Maps

**Comment by Clari-zz** [comment]
Não sei atribuir para bug, alguém poderia fazer por favor e depois explicar?

**Comment by ghost** [comment]
Não consigo reproduzir o erro. Encontrei os links errados mas me parece que foi algum problema na hora de copiar e colar no campo do markdown.
