### ISSUE TITLE
As fotos nas páginas dos usuários não existem mais

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#20]
Eu tive uma foto em meu perfil (http://maps.mootiro.org/user/2) e ela não aparece mais.

**Comment by ghost** [comment]
Nós esquecemos de migrar o relacionamento dos usuários com os files, @andersoncardoso !

@elaste, se você simplesmente quer uma foto novamente, faça um novo upload que funciona!

**Comment by andersoncardoso** [comment]
na verdade é só rodar um script bem simples (ou no fab shell mesmo) que muda o id do content type das entradas de Fileupload, exemplo:

```
for file in Fileupload.objects.filter(content_tyoe_id=id_da_tabela_user):  
   # nao lembro de era usado o id de auth.User ou do KomooProfile
   file.content_type_id = 49  # id da nova tabela de user
   file.save()
```

Isso da certo pq os object_id são iguais. Eu achei que tinha feito isso no script, me enganei.

**Comment by ghost** [comment]
Os ids não eram os mesmo de usuário na base de dados. Eles eram, na verdade, provenientes da extinta tabela user_cas_komooprofile. Tive que voltar no tempo e caçar os ids no BD na unha e fazer os updates todos manualmente.

Das 21 entradas que precisavam ser migradas, 20 foram feitas. Ficou faltando esta foto aqui: http://maps.mootiro.org/media/upload/1352240063894.jpg que a Dani vai entrar em contato com a pessoa que fez a oficina em que ela se cadastrou.

Por hora, vou fechar o ticket.
