### ISSUE TITLE
Ao logar-se no sistema o aplicativo NÃO retorna para a página atual

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#21]
Quando o usuário estiver em um conteúdo e clicar no lápis o sistema pede para ele se logar. em seguida, o sistema retorna para a página inicial (maps.mootiro.org), o certo seria, o usuário retornar ao conteudo onde ele estava, no modo de edição.

**Comment by ghost** [comment]
Feito. Falta deploy.
