### ISSUE TITLE
Mapa do projeto aparece descentralizado.

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#22]
Quando o usuário acessa o mapa do projeto http://maps.mootiro.org/project/26, clicando em "Ver todos os objetos no mapa", o aplicativo não foca onde tem o aglomerado de pontos no Rio. Esses ficam bem concentrados no canto da visualização. Os pontos devem ser visualizados no centro do mapa e com zoom máximo permitido para que todos os pontos sejam visíveis.

**Comment by ghost** [comment]
Nessa mesma tela: http://maps.mootiro.org/project/26/map
Porque a barra lateral não tem nada?

**Comment by LuizArmesto** [comment]
O mapa não aparece centralizado pois há um ponto relativo a um usuário colaborador do projeto em São Paulo. Daí surge um outro bug que é o porque a imagem do usuário não estar aparecendo (abrirei outro ticket para isso).

Sobre a barra lateral, por algum motivo que não consegui identificar de imediato um plugin do jquery não está falhando na hora de carregar. Melhor abrir um ticket específico para isso também.

Por ora vou fechar este e criar os citados acima.
