### ISSUE TITLE
Não existe mais o nome do usuário no histórico de alterações

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#23]
Quando o usuário atualiza um conteúdo aparece seu nome completo no histórico (na página do conteúdo) e nas últimas alterações (maps.mootiro.org). Deveria aparecer seu nome de usuário. O nome completo somente deve constar na página de usuário.

**Comment by LuizArmesto** [comment]
O problema é que na modelagem atual não existe mais nome de usuário.
