### ISSUE TITLE
Botão de ajuda linka pra lugar inexistente

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#24]
A página para a qual o Maps está redirecionando o usuário que resolve clicar em "ajuda" está errada. Está indo para essa: http://pt.wikiboks.org/wiki/MootiroMaps

Mas a correta é essa: http://pt.wikibooks.org/wiki/MootiroMaps 

Falta uma letra apenas ;)

**Comment by ghost** [comment]
Feito. Vou subir alterações ainda hoje.
