### ISSUE TITLE
Spock no login com Google

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#25]
Estava na página do IT3S e cliquei no botão "adicionar investimentos".
Não estava logada, então abriu o box de login. Cliquei no botão do google, para ser logada com essa conta. A próxima página foi a do Google pedindo se eu permitia aquele login. Aceitei e fui redirecionada para uma página com o Spock - e na lateral superior direita aparecia que eu estava logada.

Estava usando o Chrome. Esqueci de copiar pra cá o link e já fechei a janela =X

**Comment by LuizArmesto** [comment]
Causa provável: apps/authentication/google.py:70 retorna um dicionário, mas como a função não usa decorator deveria retornar um HttpResponse

``` python
def google_authorized(request):
[...]
    if error:
        error_description = request.GET.get('error_description', None)
        return dict(login_error='google', error_msg=error_description)  # <--- AQUI
```

**Comment by ghost** [comment]
Não é isso não, @LuizArmesto.

O problema está no fato de que a url que está no parâmetro next (que é um parâmetro GET) receberá parâmetros GET:

http://maps.mootiro.org/user/login?next=/investment/new?type=organization&obj=253

Consequência disso é que o endpoint /user/login consome o parâmetro GET que deveria ser consumido pelo endpoint em next (=/investment/new).

Não consegui resolver isso. Alguma ideia?

**Comment by andersoncardoso** [comment]
se vc fizer um urlencode no next deve funcioar.

**Comment by ghost** [comment]
Pra mim urlencode era montar a estrutura ?key1=value1&key2=value2 
Mas isso já está feito, então como faço um urlencode?

**Comment by andersoncardoso** [comment]
http://www.w3schools.com/tags/ref_urlencode.asp

substituir os carascteres ?, = & pelos seus equivalentes: %3F, %3D, %26. tem funções prontas tanto no python quanto no js que fazem isso.

No exemplo que vc deu, ficaria algo do tipo:
http://maps.mootiro.org/user/login?next=/investment/new%3Ftype%3Dorganization%26obj%3D253

**Comment by ghost** [comment]
Hum... teoricamente, isso deveria funcionar se eu acessar direto a url que
vc postou, não? (mas não funfa)
O código do decorator que faz o redirecionamento é esse:

def login_required(func=None):
    '''Decorator that requires a valid user in request.'''
    def wrapped_func(request, _a, *_kw):
        if not request.user.is_authenticated():
            next = request.get_full_path()
            url = reverse('user_login') + '?next=' + next
            return redirect(url)
        else:
            return func(request, _a, *_kw)
    return wrapped_func

2012/12/4 Anderson Pierre Cardoso notifications@github.com

> http://www.w3schools.com/tags/ref_urlencode.asp
> 
> substituir os carascteres ?, = & pelos seus equivalentes: %3F, %3D, %26.
> tem funções prontas tanto no python quanto no js que fazem isso.
> 
> No exemplo que vc deu, ficaria algo do tipo:
> 
> http://maps.mootiro.org/user/login?next=/investment/new%3Ftype%3Dorganization%26obj%3D253
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/25#issuecomment-11005539.

## 

*"Porque desde a antigüidade não se ouviu, nem com ouvidos se percebeu, nem
com os
olhos se viu um Deus além de ti que trabalha para aquele que nele espera."
- Isaías 64:4
  *
  _André Casimiro._

**Comment by andersoncardoso** [comment]
url = reverse('user_login') + '?next=' + urlencode(next)

nos lugares que vc receber  o parametro next: 

next = urldecode(request.GET('next'))

...

**Comment by ghost** [comment]
@andersoncardoso acho que vc estava se referindo a quote/unquote ao invés de urlencode/urldecode.

Acabei de tentar, e não funcionou. Parece que o navegador interpreta essa codifiação também.
Repetindo, o problema é que:

Ao acessar
http://maps.mootiro.org/user/login?next=/investment/new%3Ftype%3Dorganization%26obj%3D253

O parâmetro GET obj=53 é passado para http://maps.mootiro.org/user/login ao invés de fazer parte do parâmetro next.

**Comment by ghost** [comment]
Tinha que fazer url encode/quote sim! Eu estava errando o lugar de fazer isso.

Feito, mas falta deploy.
