### ISSUE TITLE
Sistema manda também notificações sobre mudanças em conteúdos que o próprio usuário fez

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#27]
Eu recebi o seguinte e-mail:

Olá Daniela Mattern,

Alguns objetos que você está seguindo no MootiroMaps foram atualizados:
-  Atualização em Organization : http://maps.mootiro.org/organization/1941

Visite-nos e veja as novidades.
atenciosamente,

a equipe IT3S.

Eu fiz a atualização nesse objeto e não deveria ser notificada ...

**Comment by ghost** [comment]
Feito.
