### ISSUE TITLE
Default do modo de edição deve ser o satélite

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#28]
- ao entrar no modo de editar um ponto, o sistema sempre muda para o modo limpo. Deve manter o satélite pra edição: geralmente queremos marcar as casas ou parques. Sempre preciso depois clicar em híbrido para poder começar a edição.

**Comment by ghost** [comment]
A implementação correta é manter o último estado do mapa, salvando um cookie.
Como essa já era nossa intenção inicial, mudei de enhancement para bug.

**Comment by ghost** [comment]
@LuizArmesto algum andamento nessa issue aqui?

**Comment by LuizArmesto** [comment]
Está em aberto. Não trabalhei nela ainda.

**Comment by LuizArmesto** [comment]
Essa feature acabou ficando de fora quando refatorei o código do mapa, por isso não salvava mais o tipo selecionado. 

Feito.
