### ISSUE TITLE
Ao clicar no título do objeto no balão no mapa, usuário não pode abrir o link em uma nova aba

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#30]
Não está disponível o menu de contexto e o usuário não pode abrir em nova aba o conteúdo.

**Comment by LuizArmesto** [comment]
O menu de contexto é retirado pelo próprio google maps e não é fornecida nenhuma função na api para ativá-lo novamente de modo fácil. 

Para abrir o link em uma nova aba sempre é possível usar o botão do meio do mouse ou segurar a tecla ctrl enquanto clica.
