### ISSUE TITLE
O markdown deve permitir alguns HTMLs

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#32]
Para poder citar fontes precisamos de <sup><\sup> e também deve ter uma possibilidade de colocar uma âncora para dentro da página (seção de referências). Futuramente seria legal, nosso editor ter uma botão que insere essa formatação automaticamente.

**Comment by andersoncardoso** [comment]
ou permitimos html, ou não, da forma como é hj não da pra ter uma 'whitelist' de tags permitidas.

é só citar como num email, por exemplo assim[1], ou então assim[2]

Referencias:
[1] referencia aqui
[2] outra referencia aqui

**Comment by elaste** [comment]
ok. tem essa possibilidade. concordo. Vejo também a necessidade de poder colocar uma tabela para os dados do censo escolar. Como fazemos? entra nessa coisa de substituir esse editor mais pra frente, né? Você conhece alternativas, para podermos iniciar essa análise de requisitos?

**Comment by ghost** [comment]
Permitir HTML é completamente inseguro. Já estamos nos acostumando com mediawiki, poderia ser uma opção.
Um link que pode ajudar a ver as possibilidades: http://johnmacfarlane.net/pandoc/try

**Comment by ghost** [comment]
O markdown por padrão permite html, mas isso é uma falha muito grande de segurança.
O jeito é escolher uma sintaxe que atenda a todos os requisitos. Talvez seja possível migrar os conteúdos, mas certamente haverá muito trabalho manual. =/
