### ISSUE TITLE
[Importação em lote] Necessidades de alteração no código de importação

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#33]
- o caracter ' está sendo removido ao importar pro Maps. um exemplo está em http://maps.mootiro.org/organization/3841
- nas Referências o maps coloca uma linha de espaço a mais entre duas referências
- acima de ### Referências tem uma linha à mais
- abaixo de ### Referências tem uma linha à mais
- no início e no final do campo de descrição têm linhas à mais - uma no início e duas no final

**Comment by ghost** [comment]
Fixed.
