### ISSUE TITLE
campo de e-mail diferencia minúscula e maiúscula

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#34]
Na hora do usuário se registrar o maps diferencia entre maiúscula e minúscula. ainda não descobri se também permite criar conta com o mesmo e-mail sendo maiuscula. isso precisa ser desativado.

**Comment by andersoncardoso** [comment]
permite sim criar uma conta caso seja em maiuscula. Estou resolvendo isso.

**Comment by elaste** [comment]
Oi Anderson,

vc entendeu o problema?

a pessoa se registrou com a conta de email tudo maiuscula.
depois ela se logou e digitou a conta minuscula e a senha certa.
ai o sistema nao permitiu entrar.

deveria permitir que eu acesse o sistema, tanto faz se digito
3laste2000@gmail.com ou entao 3LASTE2000@GMAIL.COM ou entao um email que
contenha misturado minuscula e maiuscula.

de forma analoga, se alguem ja registrou uma conta no maps, por exemplo
3laste2000@gmail.com, 3LAste2000@gmail.com ou outras variacoes nao devem
mais ser disponiveis.

Daniela

On Mon, Dec 10, 2012 at 3:03 PM, Anderson Pierre Cardoso <
notifications@github.com> wrote:

> permite sim criar uma conta caso seja em maiuscula. Estou resolvendo isso.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/34#issuecomment-11206500.

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org
