### ISSUE TITLE
www.maps.mootiro.org não aponta para maps.mootiro.org

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#35]
Várias pessoas não sabem que não precisa mais digitar o www - fazem e caem num aviso que essa página não existe mais. devemos mudar isso e apontar para o maps.mootiro.org

**Comment by aivuk** [comment]
Cadastrei o domínio www.maps.mootiro.org e configurei o apache adicionando:

ServerAlias *.maps.mootiro.org

**Comment by andersoncardoso** [comment]
valeu Edgar =)

**Comment by elaste** [comment]
agora, quando cadastramos com google e acessamos pelo
www.maps.mootiro.orgo google manda um erro de redirect :(

On Fri, Dec 7, 2012 at 1:43 PM, Anderson Pierre Cardoso <
notifications@github.com> wrote:

> valeu Edgar =)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/35#issuecomment-11134472.

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org

**Comment by andersoncardoso** [comment]
@aivuk creio que é melhor fazermos um redirect nesse caso. Pq o google até permite que nos cadastremos uma chave de api para diferentes domínios de redireção (já fiz e já esta funcionando), mas o facebook não. O que significa que teríamos que gerenciar mutiplas chaves de api dependendo do domínio =/, nada bom. 
Então podemos fazer algo do tipo, se o usuário entrar www.maps.mootiro.org ele redireciona para maps.mootiro.org.

Edgar, Vc já fez esse tipo de redirect antes? eu dei uma pesquisada e não entendi muito, no tutorial mandava eu editar um .htaccess que eu não consegui encontrar em /etc/apache2 .
abs

**Comment by LuizArmesto** [comment]
Esquece esse .htaccess, isso é para configuração a nível de diretório, usado principalmente em servidores compartilhados nos quais não se tem acesso as configurações gerais do apache. 

Pra esse ticket a configuração é no arquivo no qual está/estará configurado o www.maps.mootiro.org no /etc/apache2/sites-available mesmo. Seria configurar a diretiva abaixo no virtualhost com o www no começo (não olhei as configs atuais, mas acho que não tem um virtualhost com o www separado do principal ainda, então não coloque essa diretiva se estiver tudo num virtualhost só com wildcard, sob pena de ter um loop infinito, crie um separado):

Redirect permanent / http://maps.mootiro.org/

**Comment by andersoncardoso** [comment]
acho que saquei, tipo isso: 
http://www.linuxquestions.org/questions/linux-software-2/apache-2-rewrite-one-domain-to-another-435793/

vou fazer isso mais de noite para não acabar derrubando o servidor enquanto alguém pode estar usando.

**Comment by aivuk** [comment]
Feito como sugerido pelo Luiz. Foi criado um novo virtualhost, www_maps que possui apenas esse redirect
