### ISSUE TITLE
Possível adição de um objeto a um projeto como anônimo

### ISSUE THREAD

**Issue by aivuk** [it3s/mootiro-maps#36]
Ao clicar em "Adicionar a um projeto" deslogado, na página de algum objeto (testei apenas em Recurso e Organização), o sistema abre a janela de login, mas por trás abre também a janela com caixa texto autocomplete pra selecionar o projeto. Fechando a janela de login e usando a caixa autocomplete, é possível adicionar o objeto em um projeto.

Para limpeza dos meus dois testes, adicionei o IT3S em:

http://maps.mootiro.org/project/5

e também o recurso "CLUBE ESCOLA JAGUARÉ".

**Comment by andersoncardoso** [comment]
Patch gerado, somente preciso das informações de aonde esta rodando o maps, e esperar uma hora que ele esteja sendo menos utilizado para conseguir fazer o deploy disso.
abs

Em 7 de dezembro de 2012 09:52, aivuk notifications@github.com escreveu:

> Ao clicar em "Adicionar a um projeto" deslogado, na página de algum objeto
> (testei apenas em Recurso e Organização), o sistema abre a janela de login,
> mas por trás abre também a janela com caixa texto autocomplete pra
> selecionar o projeto. Fechando a janela de login e usando a caixa
> autocomplete, é possível adicionar o objeto em um projeto.
> 
> Para limpeza dos meus dois testes, adicionei o IT3S em:
> 
> http://maps.mootiro.org/project/5
> 
> e também o recurso "CLUBE ESCOLA JAGUARÉ".
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/36.

## 

Anderson Pierre Cardoso
Software Engineer - IT3S / University of Sao Paulo
*
http://www.apierrecardoso.com*
twitter: _@apierre_cardoso_ https://twitter.com/#%21/apierre_cardoso

**Comment by andersoncardoso** [comment]
obs: lembrete pra mim mesmo => aplicar com -p0  :  
patch -p0 < pacthfile
