### ISSUE TITLE
Formulário de login na página "Sobre o Mootiro Maps"

### ISSUE THREAD

**Issue by aivuk** [it3s/mootiro-maps#37]
É pra ter esse formulário:

http://i.imgur.com/jwbnQ.png

no endereço:

http://maps.mootiro.org/about/about

**Comment by andersoncardoso** [comment]
Nope, não é para aparecer. Isso deve ta vindo do template global. Achei que o hotsite usasse um diferente.

**Comment by ghost** [comment]
Deployed.
