### ISSUE TITLE
Links da busca estão usando slug

### ISSUE THREAD

**Issue by LuizArmesto** [it3s/mootiro-maps#38]
Quando faz uma busca os links da janela que aparece ainda estão usando slugs, portanto todas estão indo para páginas não existentes.

**Comment by andersoncardoso** [comment]
não consegui verificar, certeza que vc fez uma nova busca? Lembre-se que as buscas ficam carregadas no localStorage. Se vc fez a busca antes de alterarmos as urls e agora soh repetir ela (apertar enter direto na caixa, ou clicar em buscar sem alterar o texto da caixa) ela retornará os resultados no formato antigo. 
Eu acabei de testar tanto no maps em produção quanto no stable local.
Estou marcando como invalid, por enquanto, até ter novas informações sobre em que cenário isso ocorreu.

**Comment by LuizArmesto** [comment]
certeza que era uma busca que eu já tinha realizado anteriormente, mas mesmo assim não deveria apresentar a url antiga que é inválida. Deveria ter um modo de invalidar os dados salvos que ficaram obsoletos/incorretos. É comum realizar a mesma busca várias vezes (pelo menos para mim é)

**Comment by andersoncardoso** [comment]
Ele não preserva um histórico de buscas. Ele somente lembra da última
busca. Só não repete a mesma imediatamente em seguida.
se vc busco 'a' e logo em seguida buscar 'a', ele retorna o mesmo resultado
cacheado. Se vc buscou 'a', em seguida buscou 'ab', e depois voltou a
buscar 'a' , ele vai refazer a busca normalmente.

Em 10 de dezembro de 2012 15:41, Luiz Armesto
notifications@github.comescreveu:

> certeza que era uma busca que eu já tinha realizado anteriormente, mas
> mesmo assim não deveria apresentar a url antiga que é inválida. Deveria ter
> um modo de invalidar os dados salvos que ficaram obsoletos/incorretos. É
> comum realizar a mesma busca várias vezes (pelo menos para mim é)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/38#issuecomment-11208554.

## 

Anderson Pierre Cardoso
Software Engineer - IT3S / University of Sao Paulo
*
http://www.apierrecardoso.com*
twitter: _@apierre_cardoso_ https://twitter.com/#%21/apierre_cardoso

**Comment by LuizArmesto** [comment]
Verifiquei aqui e refazendo a busca depois de fazer outra está ok. Foi uma coincidência de ter refeito exatamente a última busca, e ela ter sido feita anteriormente ainda na versão antiga das urls. Vou fechar como wontfix por ocorrer apenas em um caso muito específico e não vale a pena mexer nisso.

[]'s
