### ISSUE TITLE
Minimapa de organização nao mostra pontos

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#39]
Ao inserir uma nova organizacao pro mapa, o minimapa nao funciona - mostra que nao existe informacao geografica. http://maps.mootiro.org/organization/3889/

ja tentei adicionar um ponto à unidade depois, mas tambem nao aparece. julgo esse bug muito urgente.

**Comment by ghost** [comment]
Agora o mapa está aparecendo, mas sem nenhum polígono ou ponto.
Porque isso, @LuizArmesto?

**Comment by LuizArmesto** [comment]
Porque este é um bug muito específico (único pelo que eu saiba), no qual um dos branches da organização não possui informação geométrica. Visto que a existência de branches associados a uma organização é justamente para associar várias informações geométricas, a não existência desta informação não foi tratada originalmente por não ser um dos casos de uso. 

Há três modos de corrigi-lo, gastar algumas horas para contornar um uso inesperado e tratar a falta de informação geométrica em um objeto que existe apenas para conter essa informação, deletar o branch que não possui a informação geométrica (não há como fazer isso pela interface normal, teria que ser pelo admin ) ou adicionar o ponto na branch "Secretaria do Meio Ambiente" (que é a que está vazia e cujo endereço eu não possuo).

**Comment by LuizArmesto** [comment]
@andersoncardoso você vai remover os branches das organizações, certo?

Como esse bug é diretamente relacionado com a existência de branches e essa modelagem mudará, estou fechando como "wontfix". Caso os branches continuem favor reabrir.

**Comment by andersoncardoso** [comment]
OK
