### ISSUE TITLE
creation_date em User

### ISSUE THREAD

**Issue by andersoncardoso** [it3s/mootiro-maps#40]
O usuário no Maps1 está sem o campo creation_date
Para a migração destes dados precisamos ver quais dados conseguimos resgatar em um snapshot antigo do DB, de quando o user era do auth. Para os usuários que não possuem realmente a informação inserimos algum valor  qualquer (provavelmente a última data que tivermos de quando era contrib.auth)

No Maps2 já corrigi isso.

**Comment by ghost** [comment]
Novos usuários do maps 1 continuam sem creation date?

**Comment by andersoncardoso** [comment]
infelizmente sim. Vou resolver isso essa semana ainda. Precisaremos definir uma data default pra quem não tiver esse dado. Eu chutaria algo do tipo: +ou- meio do ano passado. Pode ser? (na verdade tanto faz, já que nao temos como saber esse dado)

**Comment by ghost** [comment]
Resolver essa semana significa consertar no maps 1?

**Comment by andersoncardoso** [comment]
sim consertar na branch stable. Vai pro ar quando fizermos o update. Mas
vou ter q dar uma testada cuidadosa antes pra nao quebrar o servidor de
produçao.

2013/1/23 André Casimiro notifications@github.com

> Resolver essa semana significa consertar no maps 1?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/40#issuecomment-12594453.

## 

Anderson Pierre Cardoso
Software Engineer - IT3S / University of Sao Paulo
*
http://www.apierrecardoso.com*
twitter: _@apierre_cardoso_ https://twitter.com/#%21/apierre_cardoso

**Comment by andersoncardoso** [comment]
feito. Essa atualização vai ser um pouco manual. Preciso mandar pro servidor um arquivo via scp e depois rodar o script dentro do fab shell.

**Comment by ghost** [comment]
Não sei como vc pensou o script, mas eu fiz uma previsão _básica_ para esses casos no deploy automático.
