### ISSUE TITLE
Visualização de objetos de um projeto não funciona no chrome

### ISSUE THREAD

**Issue by ghost** [it3s/mootiro-maps#41]
Utilizando o Google Chrome, vá em:

http://maps.mootiro.org/project/6

Abaixo da descrição do projeto, clique em qualquer dos botoes grandes "Comunidades", "Necessidades", "Recursos"...

A lista de objetos deveria mudar, e não ficar fixa em organizações.

Testei no Firefox e funciona.

**Comment by LuizArmesto** [comment]
Aqui funcionou.

Testei no Chromium Version 22.0.1229.94 Ubuntu 12.10 (161065) 
e no Chrome Version 25.0.1359.3 dev Ubuntu 12.10

Qual versão e sistema operacional você usou? Continua com o mesmo problema aí?

**Comment by andersoncardoso** [comment]
aqui funcionou tbm. Chrome 23.

2012/12/19 Luiz Armesto notifications@github.com

> Aqui funcionou.
> 
> Testei no Chromium Version 22.0.1229.94 Ubuntu 12.10 (161065)
> e no Chrome Version 25.0.1359.3 dev Ubuntu 12.10
> 
> Qual versão e sistema operacional você usou? Continua com o mesmo problema
> aí?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/41#issuecomment-11516798.

## 

Anderson Pierre Cardoso
Software Engineer - IT3S / University of Sao Paulo
*
http://www.apierrecardoso.com*
twitter: _@apierre_cardoso_ https://twitter.com/#%21/apierre_cardoso

**Comment by ghost** [comment]
Aqui continua não funcionando.

Google Chrome Versão 22.0.1229.94, Ubuntu 12.04

**Comment by LuizArmesto** [comment]
Confirmado.

Pode estar relacionado com #44 pois o único erro que vi no console tem a ver com o ad-gallery

**Comment by LuizArmesto** [comment]
Aqui está funcionando agora, tanto no meu notebook (v23) quanto no computador do instituto.

André, verifica quais extensões você tem instaladas no seu chrome e se continua com o mesmo problema desativando-as (ou usando um perfil limpo). Estou achando que pode ser algum bloqueador de propagandas que vê o "ad-" no nome do arquivo do "ad-gallery" e bloqueia a execução.

**Comment by ghost** [comment]
@LuizArmesto, essa foi ninja! Acertou na mosca!

Era uma extensão chamada AdBlock.

**Comment by andersoncardoso** [comment]
boa sacada @LuizArmesto
