### ISSUE TITLE
Postar no Facebook com bug

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#42]
Quando um usuário posta pelo botão do Facebook, não aparece no timeline no Facebook.

http://maps.mootiro.org/organization/4000

**Comment by ghost** [comment]
Depois de muito trabalho consegui testar isso!

O facebook fez alguma modificações na forma como tratam esses likes em novembro do ano passado. Ao que parece, nem sempre você vai aparecer no feed do cara. Somente se o facebook julgar relevante. Uma das coisas que se leva em consideração é a presença de uma série de meta informação na página para ser parseada pelo fb. Eu adicionei essas tags, testei e o post aparece no meu feed somente quando seleciono "As mais recentes" e não "Principais histórias"

Resumindo, fiz o possível.

**Comment by elaste** [comment]
que bom André!
Vou testar ...

2013/1/23 André Casimiro notifications@github.com

> Depois de muito trabalho consegui testar isso!
> 
> O facebook fez alguma modificações na forma como tratam esses likes em
> novembro do ano passado. Ao que parece, nem sempre você vai aparecer no
> feed do cara. Somente se o facebook julgar relevante. Uma das coisas que se
> leva em consideração é a presença de uma série de meta informação na página
> para ser parseada pelo fb. Eu adicionei essas tags, testei e o post aparece
> no meu feed somente quando seleciono "As mais recentes" e não "Principais
> histórias"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/42#issuecomment-12615875.

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org
