### ISSUE TITLE
Ícone de usuário não aparece em alguns mapas

### ISSUE THREAD

**Issue by LuizArmesto** [it3s/mootiro-maps#43]
Em alguns mapas tenta-se carregar uma imagem inexistente (/static/img/far/user.png).
Só corrigir a referência no código para imagem correta ou criar uma cópia do arquivo com o nome atualmente utilizado deve resolver.

ref: #22

**Comment by ghost** [comment]
Qual status disso? (não sei como testar...)

**Comment by andersoncardoso** [comment]
copiei a img nas pastas far e near.
