### ISSUE TITLE
filtro no mapa mostra somente community e esconde o resto

### ISSUE THREAD

**Issue by andersoncardoso** [it3s/mootiro-maps#48]
va ao mapa
clique em filtrar
desative organizations
reative
ira aparecer organizations que nao estavam mostrando antes

ele indica que todos estao ativos, mas somente community

**Comment by LuizArmesto** [comment]
Isso é uma falta de integração entre o filtro manual (que chamavam "camadas", é isso né?) e o "filtro automático" em função do zoom. Não é propriamente um bug. 

Dependendo do nível de zoom foi definido que devem ser exibidos, conforme vai se aproximando, apenas comunidades em clusters, depois apenas comunidades como polígonos, depois comunidades como polígonos com apenas pontos dos outros tipos de objetos, depois tudo com polígonos.

Acontece que quando você desmarca e remarca um tipo de objeto ele ignora o filtro por zoom e esconde o que já estava escondido e então exibe o que originalmente estava escondido devido o zoom.

Essa integração não foi concluída pois a parte de camadas (agora chamada de filtro) já seria reescrita, antes mesmo de iniciarmos o maps2, quando foi avaliada a inclusão da funcionalidade de camadas personalizadas, o que acabou nunca entrando em nenhum sprint.

A questão é, nas atuais condições essa integração é prioritária?

**Comment by andersoncardoso** [comment]
it's a feature, not a bug =) 

não é prioritária não. 
Pra falar a verdade acho que isso é um ponto a ser rediscutido com a Dani, seria bem simples somente mostrar tudo e pronto. O motivo pra fazer isso é somente estético, ou tem alguma vantagem de performance com isso.

**Comment by LuizArmesto** [comment]
> it's a feature, not a bug =)

Exato!!! hehehe

> Pra falar a verdade acho que isso é um ponto a ser rediscutido com a Dani, seria bem simples somente mostrar tudo e pronto.

Certamente é mais simples mostrar tudo, mas tem que ver se o mapa não fica muito poluído. Esse filtro de zoom foi algo que nunca saia exatamente como se imaginava. Pensava-se uma regra e quando ia verificar com os elementos reais cadastrados no maps sempre tinha alguns que não se encaixavam bem.

Se for manter com o filtro por zoom, ou qualquer outra regra padrão, teria que ter 3 estados para cada filtro:
- Ligado: mostra sempre;
- Desligado: não mostra nunca;
- Automático: o filtro do zoom, ou qualquer outro que acharem melhor, escolhe se mostra ou não.

O comportamento atual é estranho pela falta do estado "automático".

> O motivo pra fazer isso é somente estético, ou tem alguma vantagem de performance com isso.

O motivo principal de esconder/exibir determinados elementos de acordo com o zoom é primeiramente estético, mas chuto que como consequência acaba dando uma mera na performance, principalmente para navegar pelo mapa por ter menos elementos precisando redesenhar (é chute pois não fiz nenhuma análise de performance relativa a isso)

**Comment by ghost** [comment]
Pela discussão acima, "It's a feature, not a bug".
