### ISSUE TITLE
Tela de erro para o 502 Proxy error

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#52]
As vezes a importação não funciona devido ao Google Docs não responder no tempo determinado.

Aparece uma tela com o seguinte texto:

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /importsheet/29/insert.

Reason: Error reading from remote server

Apache/2.2.20 (Ubuntu) Server at maps.mootiro.org Port 80

Devemos substituir por uma tela com o seguinte texto:

ups, parece que a comunicação com o servidor do Google está lenta.
Sua importação não foi concluida.

Por favor, tente mais tarde.

Deve ter um botão para retornar à importação.

**Comment by ghost** [comment]
O erro acontecia por causa de uma configuração de timeout no nosso servidor. Mais especificamente na configuração dos workers do Gunicorn.

Mais em: http://stackoverflow.com/questions/11883214/efficient-handling-of-long-running-http-connections-in-an-nginx-gunicorn-django

Commit que conserta isso: e30576f1adebbb6fc7c13ea6b3b7077d6f47be2c
