### ISSUE TITLE
Desativar botão de importação enquanto os dados tiverem com problemas

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#54]
O botão de importação somente deve funcionar quando os dados estiverem ok.

**Comment by ghost** [comment]
Já funciona assim.

O problema que vc quer dizer, Dani, é que falta a identificação de um tipo de erro. Que é quando duas linhas na planilha definem o mesmo nome para 2 objetos diferentes.

**Comment by elaste** [comment]
ah, para mim o botão está ativo mesmo com vários erros no importsheet. por isso, depois vejo o Spock!

**Comment by ghost** [comment]
é, parece que me enganei em dizer que já funciona assim... reabrindo...
