### ISSUE TITLE
No balão do objeto do mapa, devemos mostrar o início do texto do campo de descrição e não da unidade

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#59]
Atualmente, aparece o texto da unidade com as palavras-chave da organização - deve aparecer o início do texto do campo de descrição

**Comment by ghost** [comment]
de descrição... da organização, vc quer dizer?

**Comment by elaste** [comment]
sim, atualmente, temos um bug, e está regularmente apresentado o texto "none"

**Comment by andersoncardoso** [comment]
como nao existem mais unidade, parece estar resolvido
eu fiz alguns tests com campos vazios e ele nao esta mais mostrando none.
