### ISSUE TITLE
SQL de exemplo de dados

### ISSUE THREAD

**Issue by aleborba** [it3s/mootiro-maps#61]
Disponibilizar um dump de exemplo da base de dados para testes reais em ambiente local.

**Comment by ghost** [comment]
@aleborba , obrigado pela disponibilidade! Foi bom ter te conhecido lá no OSJ.

Cheguei a conclusão de que não é fácil gerar um sample do banco de dados automaticamente, por causa das foreign_keys entre as tabelas. Para gerar um sample, eu teria de fazer manualmente (limpar o banco e então adicionar alguns dados via interface).

Masss, como nossos dados são abertos, gerei um dump completo do banco e degradei as informações de usuário (que são privadas). O link do commit deve aparecer aqui dentro de alguns minutos...

**Comment by ghost** [comment]
@aleborba 
Acabamos de implementar a utilização do elasticsearch para nosso sistema de busca (nem fizemos deploy ainda). Talvez seja interessante se beneficiar dele para fazer uma api, não acha?

@andersoncardoso 
O Alê quer ajudar a construir uma API para acesso aos nossos dados e comentou sobre usar o Bottle para isso. Você trabalhou com Bottle, Flask, e também foi quem implementou o uso do elasticsearch. O que teria a dizer sobre essa implementação da API?

**Comment by aleborba** [comment]
@acasimiro 
O prazer foi meu! Eu entendo sobre o sigilo e concordo com ele :+1: 
Vamos ver por aqui como dá pra tocarmos isso e vou aguardar as considerações do @andersoncardoso :)

**Comment by andersoncardoso** [comment]
apesar de possível usar o elasticsearch para isso, estariamos desvirtuando o uso pretendido dele. O elasticsearch é um serviço de indexação e busca. Se fossemos usar uma base com uma interface rest tem escolhas mais apropriadas como o couchdb e etc.
Eu acho que seria melhor usar um microframework mesmo que acessa o postgres. Bottle e Flask são as duas melhores escolhas, eu particularmente prefiro o Flask, mas tanto faz, não tenho nada contra usar o Bottle.
