### ISSUE TITLE
Mudanças na Home

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#63]
- Placeholder no campo da busca com o texto: Digite nome da organização, usuario, recurso etc.
- Apagar a palavra Notícias embaixo da janela “Projetos que usam o MootiroMaps”
- Mudar a primeira letra de “últimas atualizações” > Últimas atualizações. Está localizado ao lado de “Blog do IT3S”
- Abaixo do video na home há uma janela com a chamada “Quer ajudar? Adicione ao mapa”. É preciso trocar o “ajudar” por “participar”.

**Comment by ghost** [comment]
O Placeholder já está feito no novo design. **OK**

**Comment by andersoncardoso** [comment]
feito
