### ISSUE TITLE
Prévia visualização do  ponto no mapa 

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#64]
--> Listagens/cadastros dos objetos e prévia da visualização do ponto no mapa (esse bug atinge todas as listagens e cadastros de objetos). Pode ser visualizado em http://maps.mootiro.org/community/ e http://maps.mootiro.org/community/44/about

Tanto nas listagens dos objetos como os cadastros dos objetos, aparece a previsão do mapa sem ter a possibilidade de clicar nele para abrir o mapa. Seria legal mudar isso. Assim, as palavras ver no mapa debaixo da janela de previsão do mapa no cadastro do objeto, podem ser apagadas.

**Comment by andersoncardoso** [comment]
o comportamento do mapa é o padrão do google-maps. vc pode dar pan ou zoom no mapa. Nem mesmo sei se a gente pode mudar isso. Mesmo se puder não parece ter um consenso sobre isso.
Como as listagens vão mudar em breve, vou marcar como 'wont fix'.
