### ISSUE TITLE
Excluir botão Novo Investimento

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#67]
Em páginas como http://maps.mootiro.org/organization/1990, tirar o botão Novo Investimento dos página das organizações/página dos recursos e colocar por cima de Listagem dos investimentos http://maps.mootiro.org/investment/ (igual como nas outras listagens dos objetos).

**Comment by ghost** [comment]
A modelagem atual não permite isso. Esse problema será resolvido quando houver unificação do modelo dos objetos e relações genéricas entre eles.
