### ISSUE TITLE
Mudança de texto

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#68]
Depois da criação da nova conta no MootiroMaps, aparece o Spock, falando: “Sua conta foi criada! Mas antes de começar...”. Também o Spock diz quando o sistema está fazendo um Update: “...Mas quando voltarmos tudo estará melhor”. Usar o “mas” nas frases causa um impacto bastante negativo para o usuário. Pode-se simplesmente extrair o “mas”. Ou mudar a frase colocando uma frase mais motivada.

**Comment by ghost** [comment]
really?!
