### ISSUE TITLE
Mudança de títulos e ordem das abas na página do usuário

### ISSUE THREAD

**Issue by anapaulabrasa** [it3s/mootiro-maps#69]
Em http://maps.mootiro.org/user/edit
- mudar o título da aba "Dados pessoais" para "Administrar a senha"
- corrigir "Dados públicas" => "Dados públicos"
- mudar o ordem das abas: Dados públicos / Assinaturas / Administrar senha / Contas Externas

**Comment by LuizArmesto** [comment]
Corrigido "Dados públicas"

**Comment by ghost** [comment]
Corrigido o resto.
