### ISSUE TITLE
Conteúdo do site abaixo da barra do topo está fino no staging

### ISSUE THREAD

**Issue by aivuk** [it3s/mootiro-maps#72]
Tanto no Firefox 19.0 quanto no Chromium Version 24.0.1312.56 Ubuntu 12.04 (24.0.1312.56-0ubuntu0.12.04.1)

![maps-staging-bug-1](https://f.cloud.github.com/assets/272892/208326/5d985e00-8222-11e2-837e-941d8fc24c82.jpg)

**Comment by aivuk** [comment]
Notei agora que isso ocorreu por causa do conteúdo da caixa de tour que apareceu abaixo do screenshot:

```
Welcome to the tour!

It's a pleasure to meet you.
MootiroMaps

This is the MootiroMaps logo. You can click it anytime to get into website's homepage.
Map preview

Here is the organization in the map.
Footer

Can I bold this? Yes!
End

Feel free... stay around...
```

**Comment by ghost** [comment]
Fixed.
