### ISSUE TITLE
Exibir os tours do Ajuda automaticamente

### ISSUE THREAD

**Issue by aivuk** [it3s/mootiro-maps#74]
Acho fundamental que os tours sejam exibidos assim que o usuário acessa pela primeira vez uma área do site, como o Google faz quando coloca uma nova funcionalidade no Gmail. Deixando apenas na ajuda a probabilidade de alguém clicar é muito baixa. Conversando com a Dani concluimos que os tours que surgem automaticamente na primeira vez só deverão ser para as áreas:
- Página principal
- Mapa
- Lista de objetos
- Projetos

**Comment by ghost** [comment]
O tour não pode simplesmente começar. Tem que mostrar uma tela perguntando se o usuário quer fazer Tour, não acham?

**Comment by LuizArmesto** [comment]
Também acho que deve exibir uma tela perguntando se quer fazer o tour
