### ISSUE TITLE
Mudança em "Sobre o MootiroMaps"

### ISSUE THREAD

**Issue by aimeesf** [it3s/mootiro-maps#75]
Inserir abas para facilitar navegação entre pontos + Mudança de algumas imagens

Aimeê ainda vai fazer design

**Comment by aimeesf** [comment]
![sobre-01](https://f.cloud.github.com/assets/301256/234207/d063033c-876c-11e2-9bf4-ca2f716098fe.png)
![sobre-02](https://f.cloud.github.com/assets/301256/234212/d0cb656c-876c-11e2-9faa-34b96a3bc6ae.png)
![sobre-03](https://f.cloud.github.com/assets/301256/234208/d06cabda-876c-11e2-899f-ba2e5a733560.png)
![sobre-04](https://f.cloud.github.com/assets/301256/234209/d06f49c6-876c-11e2-8d36-08cad1309a57.png)
![sobre-05](https://f.cloud.github.com/assets/301256/234210/d07227b8-876c-11e2-931b-ada5cd86175d.png)
![sobre-06](https://f.cloud.github.com/assets/301256/234211/d073a1ce-876c-11e2-941d-8eee0cf912e2.png)

**Comment by LuizArmesto** [comment]
@acasimiro já era a página com cores diferentes no fundo, que você sugeriu, voltamos para as abas. hehe

**Comment by ghost** [comment]
@aimeesf a navegação dos links não parece abas...
@LuizArmesto bem que podia ser um scroll automático ao invés de abas, hein?! rsrs
