### ISSUE TITLE
Criador de um projeto deve receber notificaçao quando alguem adiciona um objeto ao projeto

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#76]
Quando um usuário adiciona um objeto ao projeto, o criador deve receber uma notificaçao:

Assunto: novas contribuiçoes para seu projeto {nome do projeto}

Olá {nome do usuário},

o usuário {nome do usuário} acabou de adicionar o objetos ao seu projeto {nome do projeto}:
- nome do objeto 1 (com link)
- nome do objeto 2 (com link)

Mobilize outros usuários para colaborarem com seu projeto!

Use as redes sociais para divulgar seu projeto.

Informe seus amigos e colegas sobre seu mapeamento e peça ajuda.

Comente na página do usuário {nome do usuário} (link) e peça que ele continue colaborando.

Bom trabalho.

Equipe do MootiroMaps

**Comment by ghost** [comment]
Essa "notificação" é um e-mail?

**Comment by elaste** [comment]
Discutimos que seria melhor ter um sistema de notificações internas do
MootiroMaps.

On Thu, Mar 14, 2013 at 11:59 AM, André Casimiro
notifications@github.comwrote:

> Essa "notificação" é um e-mail?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/76#issuecomment-14906904
> .

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org

**Comment by ghost** [comment]
Sim, isso com certeza. Meu ponto é... então esse ticket fica aberto até a implementação de um sistema de notificação?

**Comment by LuizArmesto** [comment]
Será feito no meppit.
