### ISSUE TITLE
Informe sobre falta de informaçoes no perfil

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#78]
Quando o usuário ainda nao tiver colocado informacoes de perfil, ao se logar ele recebe um aviso por tela float:

Você ainda não completou as informações de seu perfil!
1. Deixe um contato público para outros usuários poderem entrar em contato com você!
2. Suba uma foto ou um avatar.
3. Marque sua localização para encontrar mapeadores em sua cidade!
4. Defina suas áreas de interesse para receber informes sobre projetos de mapeamento em andamento.

Para isso deve ter um design.

**Comment by ghost** [comment]
@aimeesf fazer design e colocar um link público aqui.

**Comment by aimeesf** [comment]
http://imgur.com/a/8wbft

**Comment by LuizArmesto** [comment]
Acho uma tela float bastante intrusivo, preferiria uma barra ou uma caixinha em algum lugar da página, mas sem bloquear o conteúdo principal. Também deve ter uma opção para o usuário não receber mais esse pedido para completar o perfil.
