### ISSUE TITLE
Facilitar a adiçao de objetos ao projeto

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#79]
### Tags

Seria muito legal, poder selecionar objetos com uma tag específica e poder adicioná-los ao projeto. Atualmente, esse processo manual é muito trabalhoso.
### Poder filtrar objetos que ainda _não_ fazem parte de um projeto

Deve ser possível na listagem filtrar somente esses objetos que ainda não fazem parte de um projeto para poder adicioná-los ao projeto.

**Comment by everton137** [comment]
E talvez por projeto pode-se criar um e-mail padrão para quem inscrever-se receber. Pois um projeto poderá ter regras diferentes para colaborarem.

**Comment by LuizArmesto** [comment]
Possibilidade de adicionar o resultado de uma lista filtrada a um projeto está feito.
