### ISSUE TITLE
Poder visualizar os projetos do usuário na aba de projetos

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#80]
Quando o usuário estiver logado, na aba de projetos acima das campanhas ele deve encontrar os projetos dos quais participa.

Atualmente, esses estao no perfil dele listados, mas ir até o perfil para chegar até o projeto nao é tão intuitivo.

**Comment by ghost** [comment]
Precisamos de um design para isso, né @aimeesf?

**Comment by aimeesf** [comment]
tá no [docs](https://docs.google.com/presentation/d/1AKPmJKvX43q3PZiodHsI6RpYVzvVxhBBbdp99FdODtw/edit#slide=id.gb2bb2ed9_11), slide 42

**Comment by ghost** [comment]
Está feito.
