### ISSUE TITLE
Ao cancelar uma importação relacionamentos com o projeto não são desfeitos

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#84]
Quando se importa objetos para um projeto e depois cancela-se a importação, os objetos então importados são removidos do sistema mas permanece alguma referencia a eles no projeto. Quando abrimos o formulário de edição do projeto vemos este resquício como items em branco na lista de relacionamentos.

Issue editada. Conteúdo original:

> **Bug na lista dos objetos associados ao projeto**
> 
> Na lista dos objetos associados ao projeto aparecem várias organizações sem nome. O que aconteceu?
> 
> Vejam um exemplo:
> http://maps.mootiro.org/project/35/edit

**Comment by LuizArmesto** [comment]
Eu não tenho acesso ao /edit para poder confirmar ou não...

**Comment by ghost** [comment]
Tinha feito um comentário estúpido. Apaguei. xD

**Comment by LuizArmesto** [comment]
Esse projeto teve importação cancelada?

**Comment by elaste** [comment]
Oi Luiz,

sim, cancelamos a importação uma vez.

Daniela

2013/3/12 Luiz Armesto notifications@github.com

> Esse projeto teve importação cancelada?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/84#issuecomment-14795806
> .

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org

**Comment by ghost** [comment]
Feito
