### ISSUE TITLE
Visualização de organizações no mapa deixou de ser um ponto e virou um ícone

### ISSUE THREAD

**Issue by ghost** [it3s/mootiro-maps#85]
_Provavelmente_ como efeito colateral da remoção das "organization branch", a visualização das organizações no mapa não é mais um ponto roxo, mas um ícone do símbolo de Organizações.

O sistema deve voltar a exibir pontos.

Veja em http://staging.maps.mootiro.org/map/ e procure organizações no mapa.

**Comment by andersoncardoso** [comment]
@LuizArmesto depois da retirada dos branches o comportamento de organization no mapa ficou diferente do resto. Sempre aparece o icone de organization grande e etc. Vc pode dar um olhada nisso?
vou tentar ajustar a parte do balão eu mesmo, mas as partes mais arcanas do mapa acho melhor deixar pra vc.

**Comment by andersoncardoso** [comment]
somente renomei o arquivo na pasta far e pareceu funcionar. Então vou fechar o issue
