### ISSUE TITLE
Visualização errada na galeria na pág. de objeto

### ISSUE THREAD

**Issue by aimeesf** [it3s/mootiro-maps#86]
![Screen shot 2013-03-05 at 19 51 27](https://f.cloud.github.com/assets/301256/225052/c5620e6a-85e6-11e2-9459-26f283d04339.png)

Chrome Version 25.0.1364.152
Mac OS X 10.6.8

**Comment by ghost** [comment]
Qual o link?

**Comment by aimeesf** [comment]
nesse caso, http://maps.mootiro.org/resource/1291

mas já vi em outras páginas

**Comment by ghost** [comment]
Aqui está normal... =/

**Comment by LuizArmesto** [comment]
aposto que é a combinação "ad-gallery + Adblock plus".

**Comment by aimeesf** [comment]
desativei o adblock e agora está na posição correta, mas as setas não funcionam

**Comment by andersoncardoso** [comment]
modifiquei o ad-gallery para spock-gallery
agora parece funcionar com o ad-block
