### ISSUE TITLE
Mapa: erro ao adicionar uma linha

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#90]
Ao mapear uma linha no sistema, o sistema somente permite "avançar" quando for finalizado o polígono. Depois do segundo ponto mapeado, a opção avançar já deve ser ativa.

O erro acontece com o mapeamento de recursos e necessidades.

**Comment by LuizArmesto** [comment]
O botão de avançar só é ativado quando se termina de desenhar a linha. Há dois modos de se terminar o desenho, um é clicando no primeiro ponto adicionado (que seria o "finalizar polígono") e o outro é dando um clique duplo quando for escolher o último ponto.
