### ISSUE TITLE
importações não aparecem na thread de últimas atualizações

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#93]
Na thread de últimas atualizações não aparecem as importações que o usuário realiza

**Comment by ghost** [comment]
Qual a tela? Para mim aparece tanto na página geral de atualizações quanto na página do usuário.

**Comment by elaste** [comment]
na versão em produção não aparece. Tô me referindo à pagina do usuário e
página de updates.

On Thu, Mar 14, 2013 at 12:01 PM, André Casimiro
notifications@github.comwrote:

> Qual a tela? Para mim aparece tanto na página geral de atualizações quanto
> na página do usuário.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/it3s/mootiro-maps/issues/93#issuecomment-14907021
> .

## 

Daniela Mattern
Coordenadora Geral
IT3S - Instituto de Fomento à Tecnologia do Terceiro Setor
Rua Emiliano Cardoso de Mello, 34
Vila Butantã
CEP: 05360-000
São Paulo - SP
Brasil
Fone: 0055-11-34768025
Celular: 0055-11-987 356 563

Siga nosso Twitter https://twitter.com/#%21/it3s | Acompanhe nosso
Facebook http://www.facebook.com/IT3S.org
mootiro.org
it3s.org

**Comment by LuizArmesto** [comment]
Aqui na minha instância de desenvolvimento aparece "N OBJETOS importados(as) ao projeto PROJETO" (onde N é um número, OBJETOS é o nome do tipo do objeto importado e PROJETO é o nome, com link, para o projeto no qual foram importados) tanto na lista geral quanto na do usuário.

Em tempo, vi em produção e tem atualização de importação na página da Clariane, por exemplo: http://maps.mootiro.org/user/185

**Comment by ghost** [comment]
A Dani se confundiu mesmo. =P
