### ISSUE TITLE
Mudança no polígono da necessidade não persiste

### ISSUE THREAD

**Issue by elaste** [it3s/mootiro-maps#98]
Quando o usuário alterar um polígono de uma necessidade, a edição não persiste ao salvar o polígono

**Comment by elaste** [comment]
@LuizArmesto, vc acha que esse bug-fix pode entrar no próximo deploy? esse bug é bastante crítico.

**Comment by LuizArmesto** [comment]
Se a unificação de modelos for entrar em produção é bem provável que esse bug deixe de existir. Só vale a penar investigar este bug se a unificação não for entrar.
